- hosts: all
  tasks:
    - name: patch yum 
      become: yes
      shell: sed 's/repo_gpgcheck=1/repo_gpgcheck=0/g' /etc/yum.repos.d/kubernetes.repo 
    - name: remove kubelet
      become: yes
      shell: yum remove -y kubelet kubectl kubeadm
    - name: update keys
      become: yes
      shell: cat /users/username/.ssh/authorized_keys >> /root/.ssh/authorized_keys
    - name: update firewall
      become: yes
      shell: systemctl stop firewalld
    - name: update firewall
      become: yes
      shell: systemctl disable firewalld
    - name: create folders
      become: yes
      shell: mkdir -p /var/lib/docker
    - name: increase size
      become: yes
      shell: /usr/local/etc/emulab/mkextrafs.pl /var/lib/docker
      
